# Alpaca-py stock trading basic

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/alpacahq/alpaca-py/blob/master/examples/stocks/stocks-trading-basic.ipynb)

- This notebook shows how to use alpaca-py with stock trading API endpoints
- Please use ``paper account``. Please ``DO NOT`` use this notebook with live account. In this notebook, we place orders for stocks as an example.

In [1]:
# Please change the following to your own PAPER api key and secret
# or set them as environment variables (ALPACA_API_KEY, ALPACA_SECRET_KEY).
# You can get them from https://alpaca.markets/

api_key = "PKRLCOBFKJ76KCBU2HDF5IOZEB"
secret_key = "7ZuuywsgL6fPhLLcJm2bdbASmVnTgB3tHBKwwsPqEQWW"

#### We use paper environment for this example ####
paper = True # Please do not modify this. This example is for paper trading only.
####

# Below are the variables for development this documents
# Please do not change these variables
trade_api_url = None
trade_api_wss = None
data_api_url = None
stream_data_wss = None

In [2]:
import os

if api_key is None:
    api_key = os.environ.get('ALPACA_API_KEY')

if secret_key is None:
    secret_key = os.environ.get('ALPACA_SECRET_KEY')

In [3]:
# install alpaca-py if it is not available
try:
    import alpaca
except ImportError:
    !python3 -m pip install alpaca-py
    import alpaca

Defaulting to user installation because normal site-packages is not writeable
Collecting alpaca-py
  Downloading alpaca_py-0.43.2-py3-none-any.whl (122 kB)
     |████████████████████████████████| 122 kB 9.3 MB/s eta 0:00:01
Collecting pydantic<3.0.0,>=2.0.3
  Downloading pydantic-2.12.4-py3-none-any.whl (463 kB)
     |████████████████████████████████| 463 kB 40.9 MB/s eta 0:00:01
Collecting pandas>=1.5.3
  Downloading pandas-2.3.3-cp39-cp39-macosx_11_0_arm64.whl (10.8 MB)
     |████████████████████████████████| 10.8 MB 20.7 MB/s eta 0:00:01
Collecting websockets>=10.4
  Downloading websockets-15.0.1-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
     |████████████████████████████████| 173 kB 32.4 MB/s eta 0:00:01
Collecting sseclient-py<2.0.0,>=1.7.2
  Downloading sseclient_py-1.8.0-py2.py3-none-any.whl (8.8 kB)
Collecting requests<3.0.0,>=2.30.0
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     |████████████████████████████████| 64 kB 8.5 MB/s  eta 0:00:01
Collecting msgpack<2.0.0,>=1.0.3
  Downloading msgpack-1.1.2-cp39-cp39-macosx_11_0_arm64.whl (84 kB)
     |████████████████████████████████| 84 kB 8.6 MB/s  eta 0:00:01
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     |████████████████████████████████| 509 kB 33.4 MB/s eta 0:00:01
Collecting tzdata>=2022.7
  Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
     |████████████████████████████████| 347 kB 21.7 MB/s eta 0:00:01
Collecting numpy>=1.22.4
  Downloading numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 8.1 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/shubbhamgupta/Library/Python/3.9/lib/python/site-packages (from pandas>=1.5.3->alpaca-py) (2.9.0.post0)
Collecting annotated-types>=0.6.0
  Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/shubbhamgupta/Library/Python/3.9/lib/python/site-packages (from pydantic<3.0.0,>=2.0.3->alpaca-py) (4.15.0)
Collecting pydantic-core==2.41.5
  Downloading pydantic_core-2.41.5-cp39-cp39-macosx_11_0_arm64.whl (1.9 MB)
     |████████████████████████████████| 1.9 MB 16.5 MB/s eta 0:00:01
Collecting typing-inspection>=0.4.2
  Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.3->alpaca-py) (1.15.0)
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
     |████████████████████████████████| 129 kB 36.8 MB/s eta 0:00:01
Collecting certifi>=2017.4.17
  Downloading certifi-2025.10.5-py3-none-any.whl (163 kB)
     |████████████████████████████████| 163 kB 28.3 MB/s eta 0:00:01
Collecting idna<4,>=2.5
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     |████████████████████████████████| 71 kB 16.2 MB/s eta 0:00:01
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.4-cp39-cp39-macosx_10_9_universal2.whl (209 kB)
     |████████████████████████████████| 209 kB 44.9 MB/s eta 0:00:01
Installing collected packages: urllib3, tzdata, typing-inspection, pytz, pydantic-core, numpy, idna, charset-normalizer, certifi, annotated-types, websockets, sseclient-py, requests, pydantic, pandas, msgpack, alpaca-py
Successfully installed alpaca-py-0.43.2 annotated-types-0.7.0 certifi-2025.10.5 charset-normalizer-3.4.4 idna-3.11 msgpack-1.1.2 numpy-2.0.2 pandas-2.3.3 pydantic-2.12.4 pydantic-core-2.41.5 pytz-2025.2 requests-2.32.5 sseclient-py-1.8.0 typing-inspection-0.4.2 tzdata-2025.2 urllib3-2.5.0 websockets-15.0.1
WARNING: You are using pip version 21.2.4; however, version 25.3 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

In [4]:
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from alpaca.trading.client import TradingClient
from alpaca.data.timeframe import TimeFrame, TimeFrameUnit
from alpaca.data.historical.corporate_actions import CorporateActionsClient
from alpaca.data.historical.stock import StockHistoricalDataClient
from alpaca.trading.stream import TradingStream
from alpaca.data.live.stock import StockDataStream

from alpaca.data.requests import (
    CorporateActionsRequest,
    StockBarsRequest,
    StockQuotesRequest,
    StockTradesRequest,
)
from alpaca.trading.requests import (
    ClosePositionRequest,
    GetAssetsRequest,
    GetOrdersRequest,
    LimitOrderRequest,
    MarketOrderRequest,
    StopLimitOrderRequest,
    StopLossRequest,
    StopOrderRequest,
    TakeProfitRequest,
    TrailingStopOrderRequest,
)
from alpaca.trading.enums import (
    AssetExchange,
    AssetStatus,
    OrderClass,
    OrderSide,
    OrderType,
    QueryOrderStatus,
    TimeInForce,
)

/Users/shubbhamgupta/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [5]:
# to run async code in jupyter notebook
import nest_asyncio
nest_asyncio.apply()

In [6]:
# check version of alpaca-py
alpaca.__version__

'0.43.2'

# Trading Client

In [7]:
# setup clients
trade_client = TradingClient(api_key=api_key, secret_key=secret_key, paper=paper, url_override=trade_api_url)

In [8]:
# check trading account
# You can check definition of each field in the following documents
# ref. https://docs.alpaca.markets/docs/account-plans
# ref. https://docs.alpaca.markets/reference/getaccount-1
acct = trade_client.get_account()
acct

{   'account_blocked': False,
    'account_number': 'PA3FYUNWAZZP',
    'accrued_fees': '0',
    'buying_power': '200000',
    'cash': '100000',
    'created_at': datetime.datetime(2024, 5, 27, 13, 50, 50, 580455, tzinfo=TzInfo(0)),
    'crypto_status': <AccountStatus.ACTIVE: 'ACTIVE'>,
    'currency': 'USD',
    'daytrade_count': 0,
    'daytrading_buying_power': '0',
    'equity': '100000',
    'id': UUID('4d77d52d-e1f5-40c0-a50f-03efe27dddfd'),
    'initial_margin': '0',
    'last_equity': '100000',
    'last_maintenance_margin': '0',
    'long_market_value': '0',
    'maintenance_margin': '0',
    'multiplier': '2',
    'non_marginable_buying_power': '100000',
    'options_approved_level': 3,
    'options_buying_power': '100000',
    'options_trading_level': 3,
    'pattern_day_trader': False,
    'pending_transfer_in': None,
    'pending_transfer_out': None,
    'portfolio_value': '100000',
    'regt_buying_power': '200000',
    'short_market_value': '0',
    'shorting_enabled': True,
    'sma': '100000',
    'status': <AccountStatus.ACTIVE: 'ACTIVE'>,
    'trade_suspended_by_user': False,
    'trading_blocked': False,
    'transfers_blocked': False}

In [9]:
# check account configuration
# ref. https://docs.alpaca.markets/reference/getaccountconfig-1
acct_config = trade_client.get_account_configurations()
acct_config

{   'dtbp_check': <DTBPCheck.ENTRY: 'entry'>,
    'fractional_trading': True,
    'max_margin_multiplier': '4',
    'max_options_trading_level': None,
    'no_shorting': False,
    'pdt_check': <PDTCheck.ENTRY: 'entry'>,
    'ptp_no_exception_entry': False,
    'suspend_trade': False,
    'trade_confirm_email': <TradeConfirmationEmail.ALL: 'all'>}

In [10]:
# set account configuration
# ref. https://docs.alpaca.markets/reference/patchaccountconfig-1
req = acct_config
req.fractional_trading = not req.fractional_trading # toggle fractional trading
acct_config_new = trade_client.set_account_configurations(req)
display(acct_config_new)

# revert changes
req = acct_config_new
req.fractional_trading = not req.fractional_trading # toggle fractional trading
acct_config_reverted = trade_client.set_account_configurations(req)
display(acct_config_reverted)

{   'dtbp_check': <DTBPCheck.ENTRY: 'entry'>,
    'fractional_trading': False,
    'max_margin_multiplier': '4',
    'max_options_trading_level': None,
    'no_shorting': False,
    'pdt_check': <PDTCheck.ENTRY: 'entry'>,
    'ptp_no_exception_entry': False,
    'suspend_trade': False,
    'trade_confirm_email': <TradeConfirmationEmail.ALL: 'all'>}

{   'dtbp_check': <DTBPCheck.ENTRY: 'entry'>,
    'fractional_trading': True,
    'max_margin_multiplier': '4',
    'max_options_trading_level': None,
    'no_shorting': False,
    'pdt_check': <PDTCheck.ENTRY: 'entry'>,
    'ptp_no_exception_entry': False,
    'suspend_trade': False,
    'trade_confirm_email': <TradeConfirmationEmail.ALL: 'all'>}

In [11]:
# get list of assets which are us_equity (default), active, and in NASDAQ
# ref. https://docs.alpaca.markets/reference/get-v2-assets-1
req = GetAssetsRequest(
  # asset_class=AssetClass.US_EQUITY,  # default asset_class is us_equity
  status=AssetStatus.ACTIVE,
  exchange=AssetExchange.NASDAQ,
)
assets = trade_client.get_all_assets(req)
assets[:2]

[{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'attributes': [],
     'easy_to_borrow': False,
     'exchange': <AssetExchange.NASDAQ: 'NASDAQ'>,
     'fractionable': False,
     'id': UUID('a246d8bd-cb63-49e9-ac8b-7cd7cb637f96'),
     'maintenance_margin_requirement': 100.0,
     'marginable': False,
     'min_order_size': None,
     'min_trade_increment': None,
     'name': 'CBL International Limited Ordinary Shares',
     'price_increment': None,
     'shortable': False,
     'status': <AssetStatus.ACTIVE: 'active'>,
     'symbol': 'BANL',
     'tradable': False},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'attributes': [],
     'easy_to_borrow': False,
     'exchange': <AssetExchange.NASDAQ: 'NASDAQ'>,
     'fractionable': False,
     'id': UUID('2acbbcd2-41d5-47d0-8fc3-753bd598cbda'),
     'maintenance_margin_requirement': 100.0,
     'marginable': False,
     'min_order_size': None,
     'min_trade_increment': None,
     'name': 'Akanda Corp. Common Shares',
     'price_increment': None,
     'shortable': False,
     'status': <AssetStatus.ACTIVE: 'active'>,
     'symbol': 'AKAN',
     'tradable': False}]

### Orders

In [12]:
# we will place orders which Alapca trading platform supports
# - order classes: simple, bracket, oco, oto
# - order types: market, limit, stop, stop_limit, trailing_stop
#
# please refer to the following documents for more details
# ref. https://docs.alpaca.markets/docs/orders-at-alpaca
# ref. https://docs.alpaca.markets/reference/postorder
#
# we will also use fractional trading capability of Alpaca trading platform in this example
# ref. https://docs.alpaca.markets/docs/fractional-trading

# we will place orders for symbol: SPY in this example
symbol = "SPY"

In [13]:
# simple, market order, fractional qty
# Alpaca trading platform support fractional trading by default
# you can specify:
# fractional qty (e.g. 0.01 qty) in the order request (which is shown in this example)
# or notional value (e.g. 100 USD) (which is in the next example)
#
# If you have an error of `qty must be integer`,
# please try to `Reset Account` of your paper account via the Alpaca Trading API dashboard
req = MarketOrderRequest(
    symbol = symbol,
    qty = 5.5,
    side = OrderSide.BUY,
    type = OrderType.MARKET,
    time_in_force = TimeInForce.DAY,
)
res = trade_client.submit_order(req)
res

{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
    'canceled_at': None,
    'client_order_id': 'e5729d6a-5321-4642-8969-8db05d8261ad',
    'created_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 629700, tzinfo=TzInfo(0)),
    'expired_at': None,
    'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': UUID('b5223990-a988-4c1a-a718-1dcb9297c380'),
    'legs': None,
    'limit_price': None,
    'notional': None,
    'order_class': <OrderClass.SIMPLE: 'simple'>,
    'order_type': <OrderType.MARKET: 'market'>,
    'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
    'qty': '5.5',
    'ratio_qty': None,
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': <OrderSide.BUY: 'buy'>,
    'status': <OrderStatus.ACCEPTED: 'accepted'>,
    'stop_price': None,
    'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 629700, tzinfo=TzInfo(0)),
    'symbol': 'SPY',
    'time_in_force': <TimeInForce.DAY: 'day'>,
    'trail_percent': None,
    'trail_price': None,
    'type': <OrderType.MARKET: 'market'>,
    'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 631526, tzinfo=TzInfo(0))}

In [14]:
# simple, market order, notional
# Alpaca trading platform support fractional trading by default
# you can specify:
# fractional qty (e.g. 0.01 qty) in the order request (which is in the example above)
# or notional value (e.g. 100 USD) (which is in this example)
req = MarketOrderRequest(
    symbol = symbol,
    notional = 1.11,  # notional is specified in USD, here we specify $1.11
    side = OrderSide.BUY,
    type = OrderType.MARKET,
    time_in_force = TimeInForce.DAY,
)
res = trade_client.submit_order(req)
res

{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
    'canceled_at': None,
    'client_order_id': 'c9cecfd1-14c3-4e61-8ae6-ba13676bb217',
    'created_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766009, tzinfo=TzInfo(0)),
    'expired_at': None,
    'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': UUID('e9dc3750-5724-4583-9233-53ebd343e796'),
    'legs': None,
    'limit_price': None,
    'notional': '1.11',
    'order_class': <OrderClass.SIMPLE: 'simple'>,
    'order_type': <OrderType.MARKET: 'market'>,
    'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
    'qty': None,
    'ratio_qty': None,
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': <OrderSide.BUY: 'buy'>,
    'status': <OrderStatus.ACCEPTED: 'accepted'>,
    'stop_price': None,
    'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766009, tzinfo=TzInfo(0)),
    'symbol': 'SPY',
    'time_in_force': <TimeInForce.DAY: 'day'>,
    'trail_percent': None,
    'trail_price': None,
    'type': <OrderType.MARKET: 'market'>,
    'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766871, tzinfo=TzInfo(0))}

In [15]:
# simple, limit order, fractional qty
req = LimitOrderRequest(
    symbol = symbol,
    qty = 0.01,
    limit_price = 550.25,
    side = OrderSide.BUY,
    type = OrderType.LIMIT,
    time_in_force = TimeInForce.DAY,
)
res = trade_client.submit_order(req)
res

{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
    'canceled_at': None,
    'client_order_id': '7162b74c-ef14-459e-b3bd-569fd459d8fd',
    'created_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82042, tzinfo=TzInfo(0)),
    'expired_at': None,
    'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': UUID('45e8f45c-851a-4982-bd4a-a7b8a338926e'),
    'legs': None,
    'limit_price': '550.25',
    'notional': None,
    'order_class': <OrderClass.SIMPLE: 'simple'>,
    'order_type': <OrderType.LIMIT: 'limit'>,
    'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
    'qty': '0.01',
    'ratio_qty': None,
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': <OrderSide.BUY: 'buy'>,
    'status': <OrderStatus.ACCEPTED: 'accepted'>,
    'stop_price': None,
    'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82042, tzinfo=TzInfo(0)),
    'symbol': 'SPY',
    'time_in_force': <TimeInForce.DAY: 'day'>,
    'trail_percent': None,
    'trail_price': None,
    'type': <OrderType.LIMIT: 'limit'>,
    'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82609, tzinfo=TzInfo(0))}

In [16]:
# stop order
req = StopOrderRequest(
                    symbol = symbol,
                    qty = 1,
                    side = OrderSide.BUY,
                    time_in_force = TimeInForce.GTC,
                    stop_price = 600
                    )

res = trade_client.submit_order(req)
res

{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
    'canceled_at': None,
    'client_order_id': '05b197e9-f672-43c1-a39e-23ac1a65a101',
    'created_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 893869, tzinfo=TzInfo(0)),
    'expired_at': None,
    'expires_at': datetime.datetime(2026, 2, 6, 21, 0, tzinfo=TzInfo(0)),
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': UUID('8444d5ce-f4b1-47fa-8db4-1bf088362782'),
    'legs': None,
    'limit_price': None,
    'notional': None,
    'order_class': <OrderClass.SIMPLE: 'simple'>,
    'order_type': <OrderType.STOP: 'stop'>,
    'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
    'qty': '1',
    'ratio_qty': None,
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': <OrderSide.BUY: 'buy'>,
    'status': <OrderStatus.ACCEPTED: 'accepted'>,
    'stop_price': '600',
    'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 893869, tzinfo=TzInfo(0)),
    'symbol': 'SPY',
    'time_in_force': <TimeInForce.GTC: 'gtc'>,
    'trail_percent': None,
    'trail_price': None,
    'type': <OrderType.STOP: 'stop'>,
    'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 894397, tzinfo=TzInfo(0))}

In [17]:
# stop limit order
req = StopLimitOrderRequest(
                    symbol = symbol,
                    qty = 1,
                    side = OrderSide.BUY,
                    time_in_force = TimeInForce.GTC,
                    limit_price = 550,
                    stop_price = 600
                    )

res = trade_client.submit_order(req)
res

{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
    'canceled_at': None,
    'client_order_id': '740b06c3-9e9e-4246-8db4-7f511125bc76',
    'created_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 291692, tzinfo=TzInfo(0)),
    'expired_at': None,
    'expires_at': datetime.datetime(2026, 2, 6, 21, 0, tzinfo=TzInfo(0)),
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': UUID('45a16a51-76e0-48c4-8ada-f3e90cde26af'),
    'legs': None,
    'limit_price': '550',
    'notional': None,
    'order_class': <OrderClass.SIMPLE: 'simple'>,
    'order_type': <OrderType.STOP_LIMIT: 'stop_limit'>,
    'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
    'qty': '1',
    'ratio_qty': None,
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': <OrderSide.BUY: 'buy'>,
    'status': <OrderStatus.ACCEPTED: 'accepted'>,
    'stop_price': '600',
    'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 291692, tzinfo=TzInfo(0)),
    'symbol': 'SPY',
    'time_in_force': <TimeInForce.GTC: 'gtc'>,
    'trail_percent': None,
    'trail_price': None,
    'type': <OrderType.STOP_LIMIT: 'stop_limit'>,
    'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 292224, tzinfo=TzInfo(0))}

In [18]:
# bracket order with both stop loss and take profit
req = MarketOrderRequest(
                    symbol = symbol,
                    qty = 5,
                    side = OrderSide.BUY,
                    time_in_force = TimeInForce.DAY,
                    order_class = OrderClass.BRACKET,
                    take_profit = TakeProfitRequest(limit_price=600),
                    stop_loss = StopLossRequest(stop_price=300)
)
res = trade_client.submit_order(req)
res

APIError: {"base_price":"672.36","code":42210000,"message":"take_profit.limit_price must be \u003e= base_price + 0.01"}

In [19]:
# oto order with stop loss
req = LimitOrderRequest(
                    symbol = symbol,
                    qty = 1,
                    limit_price = 500,
                    side = OrderSide.BUY,
                    time_in_force = TimeInForce.DAY,
                    Class = OrderClass.OTO,
                    stop_loss = StopLossRequest(stop_price = 300)
                    )

res = trade_client.submit_order(req)
res

{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
    'canceled_at': None,
    'client_order_id': 'f2568eca-ecb4-409f-b565-38872826c4a5',
    'created_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 952460, tzinfo=TzInfo(0)),
    'expired_at': None,
    'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': UUID('3ef6085a-1cb6-418c-b96e-ff88a80e3bd6'),
    'legs': None,
    'limit_price': '500',
    'notional': None,
    'order_class': <OrderClass.SIMPLE: 'simple'>,
    'order_type': <OrderType.LIMIT: 'limit'>,
    'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
    'qty': '1',
    'ratio_qty': None,
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': <OrderSide.BUY: 'buy'>,
    'status': <OrderStatus.ACCEPTED: 'accepted'>,
    'stop_price': None,
    'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 952460, tzinfo=TzInfo(0)),
    'symbol': 'SPY',
    'time_in_force': <TimeInForce.DAY: 'day'>,
    'trail_percent': None,
    'trail_price': None,
    'type': <OrderType.LIMIT: 'limit'>,
    'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 953053, tzinfo=TzInfo(0))}

In [20]:
# oco limit order
req = LimitOrderRequest(
                    symbol = symbol,
                    qty = 1,
                    limit_price = 500,
                    side = OrderSide.BUY,
                    time_in_force = TimeInForce.DAY,
                    Class = OrderClass.OCO
                    )

res = trade_client.submit_order(req)
res

{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
    'canceled_at': None,
    'client_order_id': '06c06abc-05fb-4337-8fbc-822b15d8e6d4',
    'created_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 474747, tzinfo=TzInfo(0)),
    'expired_at': None,
    'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
    'extended_hours': False,
    'failed_at': None,
    'filled_at': None,
    'filled_avg_price': None,
    'filled_qty': '0',
    'hwm': None,
    'id': UUID('ec44a8b9-1850-48c3-8e62-62d9b29a246d'),
    'legs': None,
    'limit_price': '500',
    'notional': None,
    'order_class': <OrderClass.SIMPLE: 'simple'>,
    'order_type': <OrderType.LIMIT: 'limit'>,
    'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
    'qty': '1',
    'ratio_qty': None,
    'replaced_at': None,
    'replaced_by': None,
    'replaces': None,
    'side': <OrderSide.BUY: 'buy'>,
    'status': <OrderStatus.ACCEPTED: 'accepted'>,
    'stop_price': None,
    'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 474747, tzinfo=TzInfo(0)),
    'symbol': 'SPY',
    'time_in_force': <TimeInForce.DAY: 'day'>,
    'trail_percent': None,
    'trail_price': None,
    'type': <OrderType.LIMIT: 'limit'>,
    'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 475350, tzinfo=TzInfo(0))}

In [21]:
# trailing stop order
req = TrailingStopOrderRequest(
                    symbol = symbol,
                    qty = 1,
                    side = OrderSide.SELL,
                    time_in_force = TimeInForce.GTC,
                    trail_percent = 0.20 # you can also use trail_price instead of trail_percent
                    )

res = trade_client.submit_order(req)
res

APIError: {"code":40310000,"message":"cannot open a short sell while a long buy order is open"}

In [22]:
# get a list of orders including closed (e.g. filled) orders by specifying symbol
req = GetOrdersRequest(
    status = QueryOrderStatus.ALL,
    symbols = [symbol]
)
orders = trade_client.get_orders(req)
orders

[{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '06c06abc-05fb-4337-8fbc-822b15d8e6d4',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 474747, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('ec44a8b9-1850-48c3-8e62-62d9b29a246d'),
     'legs': None,
     'limit_price': '500',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.LIMIT: 'limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 474747, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.LIMIT: 'limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 475350, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': 'f2568eca-ecb4-409f-b565-38872826c4a5',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 952461, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('3ef6085a-1cb6-418c-b96e-ff88a80e3bd6'),
     'legs': None,
     'limit_price': '500',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.LIMIT: 'limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 952461, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.LIMIT: 'limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 953054, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '740b06c3-9e9e-4246-8db4-7f511125bc76',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 291692, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2026, 2, 6, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('45a16a51-76e0-48c4-8ada-f3e90cde26af'),
     'legs': None,
     'limit_price': '550',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.STOP_LIMIT: 'stop_limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': '600',
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 291692, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.GTC: 'gtc'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.STOP_LIMIT: 'stop_limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 292225, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '05b197e9-f672-43c1-a39e-23ac1a65a101',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 893870, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2026, 2, 6, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('8444d5ce-f4b1-47fa-8db4-1bf088362782'),
     'legs': None,
     'limit_price': None,
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.STOP: 'stop'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': '600',
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 893870, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.GTC: 'gtc'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.STOP: 'stop'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 894397, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '7162b74c-ef14-459e-b3bd-569fd459d8fd',
     'created_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82042, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('45e8f45c-851a-4982-bd4a-a7b8a338926e'),
     'legs': None,
     'limit_price': '550.25',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.LIMIT: 'limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '0.01',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82042, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.LIMIT: 'limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82610, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': 'c9cecfd1-14c3-4e61-8ae6-ba13676bb217',
     'created_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766010, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('e9dc3750-5724-4583-9233-53ebd343e796'),
     'legs': None,
     'limit_price': None,
     'notional': '1.11',
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.MARKET: 'market'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': None,
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766010, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.MARKET: 'market'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766872, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': 'e5729d6a-5321-4642-8969-8db05d8261ad',
     'created_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 629701, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('b5223990-a988-4c1a-a718-1dcb9297c380'),
     'legs': None,
     'limit_price': None,
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.MARKET: 'market'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '5.5',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 629701, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.MARKET: 'market'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 631526, tzinfo=TzInfo(0))}]

In [23]:
# see all open orders
req = GetOrdersRequest(
    status = QueryOrderStatus.OPEN,
    symbols = [symbol]
)
open_orders = trade_client.get_orders(req)
open_orders

[{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '06c06abc-05fb-4337-8fbc-822b15d8e6d4',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 474747, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('ec44a8b9-1850-48c3-8e62-62d9b29a246d'),
     'legs': None,
     'limit_price': '500',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.LIMIT: 'limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 474747, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.LIMIT: 'limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 29, 475350, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': 'f2568eca-ecb4-409f-b565-38872826c4a5',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 952461, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('3ef6085a-1cb6-418c-b96e-ff88a80e3bd6'),
     'legs': None,
     'limit_price': '500',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.LIMIT: 'limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 952461, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.LIMIT: 'limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 25, 953054, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '740b06c3-9e9e-4246-8db4-7f511125bc76',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 291692, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2026, 2, 6, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('45a16a51-76e0-48c4-8ada-f3e90cde26af'),
     'legs': None,
     'limit_price': '550',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.STOP_LIMIT: 'stop_limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': '600',
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 291692, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.GTC: 'gtc'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.STOP_LIMIT: 'stop_limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 7, 292225, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '05b197e9-f672-43c1-a39e-23ac1a65a101',
     'created_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 893870, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2026, 2, 6, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('8444d5ce-f4b1-47fa-8db4-1bf088362782'),
     'legs': None,
     'limit_price': None,
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.STOP: 'stop'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '1',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': '600',
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 893870, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.GTC: 'gtc'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.STOP: 'stop'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 57, 3, 894397, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': '7162b74c-ef14-459e-b3bd-569fd459d8fd',
     'created_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82042, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('45e8f45c-851a-4982-bd4a-a7b8a338926e'),
     'legs': None,
     'limit_price': '550.25',
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.LIMIT: 'limit'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '0.01',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82042, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.LIMIT: 'limit'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 58, 82610, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': 'c9cecfd1-14c3-4e61-8ae6-ba13676bb217',
     'created_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766010, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('e9dc3750-5724-4583-9233-53ebd343e796'),
     'legs': None,
     'limit_price': None,
     'notional': '1.11',
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.MARKET: 'market'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': None,
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766010, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.MARKET: 'market'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 52, 766872, tzinfo=TzInfo(0))},
 {   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
     'asset_id': UUID('b28f4066-5c6d-479b-a2af-85dc1a8f16fb'),
     'canceled_at': None,
     'client_order_id': 'e5729d6a-5321-4642-8969-8db05d8261ad',
     'created_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 629701, tzinfo=TzInfo(0)),
     'expired_at': None,
     'expires_at': datetime.datetime(2025, 11, 10, 21, 0, tzinfo=TzInfo(0)),
     'extended_hours': False,
     'failed_at': None,
     'filled_at': None,
     'filled_avg_price': None,
     'filled_qty': '0',
     'hwm': None,
     'id': UUID('b5223990-a988-4c1a-a718-1dcb9297c380'),
     'legs': None,
     'limit_price': None,
     'notional': None,
     'order_class': <OrderClass.SIMPLE: 'simple'>,
     'order_type': <OrderType.MARKET: 'market'>,
     'position_intent': <PositionIntent.BUY_TO_OPEN: 'buy_to_open'>,
     'qty': '5.5',
     'ratio_qty': None,
     'replaced_at': None,
     'replaced_by': None,
     'replaces': None,
     'side': <OrderSide.BUY: 'buy'>,
     'status': <OrderStatus.ACCEPTED: 'accepted'>,
     'stop_price': None,
     'submitted_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 629701, tzinfo=TzInfo(0)),
     'symbol': 'SPY',
     'time_in_force': <TimeInForce.DAY: 'day'>,
     'trail_percent': None,
     'trail_price': None,
     'type': <OrderType.MARKET: 'market'>,
     'updated_at': datetime.datetime(2025, 11, 9, 17, 56, 45, 631526, tzinfo=TzInfo(0))}]

In [24]:
# cancel all open orders
trade_client.cancel_orders()

[{   'body': None,
     'id': UUID('3ef6085a-1cb6-418c-b96e-ff88a80e3bd6'),
     'status': 200},
 {   'body': None,
     'id': UUID('45a16a51-76e0-48c4-8ada-f3e90cde26af'),
     'status': 200},
 {   'body': None,
     'id': UUID('45e8f45c-851a-4982-bd4a-a7b8a338926e'),
     'status': 200},
 {   'body': None,
     'id': UUID('8444d5ce-f4b1-47fa-8db4-1bf088362782'),
     'status': 200},
 {   'body': None,
     'id': UUID('b5223990-a988-4c1a-a718-1dcb9297c380'),
     'status': 200},
 {   'body': None,
     'id': UUID('e9dc3750-5724-4583-9233-53ebd343e796'),
     'status': 200},
 {   'body': None,
     'id': UUID('ec44a8b9-1850-48c3-8e62-62d9b29a246d'),
     'status': 200}]

### Positions

In [25]:
# get all open positions
# ref. https://docs.alpaca.markets/reference/getallopenpositions-1
positions = trade_client.get_all_positions()
positions

[]

In [26]:
# get positions by symbol
# ref. https://docs.alpaca.markets/reference/getopenposition-1
position = trade_client.get_open_position(symbol_or_asset_id=symbol)
position

APIError: {"code":40410000,"message":"position does not exist"}

In [27]:
# get positions by asset_id
trade_client.get_open_position(symbol_or_asset_id=position.asset_id)

NameError: name 'position' is not defined

In [ ]:
# close the position with specifying qty
# ref. https://docs.alpaca.markets/reference/deleteopenposition-1
trade_client.close_position(
    symbol_or_asset_id = symbol,
    close_options = ClosePositionRequest(
        qty = "0.01",
    )
)

# Trade Update (Stream)

With TradingStream client, you can get updates about trades

You can open this notebook in another window and run below cell to check trade updates.

In [ ]:
# subscribe trade updates
trade_stream_client = TradingStream(api_key, secret_key, paper=paper, url_override = trade_api_wss)

async def trade_updates_handler(data):
    print(data)

trade_stream_client.subscribe_trade_updates(trade_updates_handler)
trade_stream_client.run()

# Market Data (Historical)

In [28]:
# setup stock historical data client
stock_historical_data_client = StockHistoricalDataClient(api_key, secret_key, url_override = data_api_url)

In [29]:
# get historical bars by symbol
# ref. https://docs.alpaca.markets/reference/stockbars-1
now = datetime.now(ZoneInfo("America/New_York"))
req = StockBarsRequest(
    symbol_or_symbols = [symbol],
    timeframe=TimeFrame(amount = 1, unit = TimeFrameUnit.Hour), # specify timeframe
    start = now - timedelta(days = 5),                          # specify start datetime, default=the beginning of the current day.
    # end_date=None,                                        # specify end datetime, default=now
    limit = 2,                                               # specify limit
)
stock_historical_data_client.get_stock_bars(req).df

                                    open    high     low   close     volume  \
symbol timestamp
SPY    2025-11-04 18:00:00+00:00  675.98  676.42  674.71  676.15  6910755.0
       2025-11-04 19:00:00+00:00  676.11  676.68  674.58  675.17  7982042.0

                                  trade_count        vwap
symbol timestamp
SPY    2025-11-04 18:00:00+00:00     118010.0  675.598552
       2025-11-04 19:00:00+00:00     130905.0  675.734494

In [30]:
# get historical trades by symbol
req = StockTradesRequest(
    symbol_or_symbols = [symbol],
    start = now - timedelta(days = 5),                          # specify start datetime, default=the beginning of the current day.
    # end=None,                                             # specify end datetime, default=now
    limit = 2,                                                # specify limit
)
stock_historical_data_client.get_stock_trades(req).df

                                        exchange   price   size  \
symbol timestamp
SPY    2025-11-04 17:58:19.067770+00:00        P  675.77  120.0
       2025-11-04 17:58:19.067773+00:00        P  675.77   40.0

                                                     id conditions tape
symbol timestamp
SPY    2025-11-04 17:58:19.067770+00:00  52983592202566        [ ]    B
       2025-11-04 17:58:19.067773+00:00  52983592202567        [ ]    B

In [31]:
# get historical quotes by symbol
req = StockQuotesRequest(
    symbol_or_symbols = [symbol],
    start = now - timedelta(days = 5),                      # specify start datetime, default=the beginning of the current day.
    # end=None,                                             # specify end datetime, default=now
    limit = 2,                                              # specify limit
)
stock_historical_data_client.get_stock_quotes(req).df

                                         bid_price  bid_size bid_exchange  \
symbol timestamp
SPY    2025-11-04 17:58:19.067738+00:00     675.77     320.0            P
       2025-11-04 17:58:19.067768+00:00     675.77     240.0            T

                                         ask_price  ask_size ask_exchange  \
symbol timestamp
SPY    2025-11-04 17:58:19.067738+00:00     675.78     320.0            T
       2025-11-04 17:58:19.067768+00:00     675.78     320.0            T

                                        conditions tape
symbol timestamp
SPY    2025-11-04 17:58:19.067738+00:00        [R]    B
       2025-11-04 17:58:19.067768+00:00        [R]    B

In [32]:
# get latest quotes by symbol
req = StockQuotesRequest(
    symbol_or_symbols = [symbol],
)
res = stock_historical_data_client.get_stock_latest_quote(req)
res

{'SPY': {   'ask_exchange': 'V',
     'ask_price': 677.58,
     'ask_size': 40.0,
     'bid_exchange': 'V',
     'bid_price': 671.02,
     'bid_size': 280.0,
     'conditions': ['R'],
     'symbol': 'SPY',
     'tape': 'B',
     'timestamp': datetime.datetime(2025, 11, 7, 21, 57, 53, 670514, tzinfo=TzInfo(0))}}

# Market Data (Stream)

In [33]:
stock_data_stream_client = StockDataStream(api_key, secret_key, url_override = stream_data_wss)

async def stock_data_stream_handler(data):
    print(data)

symbols = [symbol]

stock_data_stream_client.subscribe_quotes(stock_data_stream_handler, *symbols)
stock_data_stream_client.subscribe_trades(stock_data_stream_handler, *symbols)

stock_data_stream_client.run()

keyboard interrupt, bye

TimeoutError:

# Corporate actions

In [34]:
corporate_actions_client = CorporateActionsClient(api_key, secret_key)
corporate_actions_client.get_corporate_actions(CorporateActionsRequest(
    start=datetime(2020, 1, 1),
    symbols=[symbol]
)).df

,id,symbol,cusip,rate,special,foreign,process_date,ex_date,record_date,payable_date
corporate_action_type,,,,,,,,,,
cash_dividends,e06f1a82-04b5-4b90-9c7b-06d22b720db1,SPY,78462F103,1.405559,False,False,2020-04-30,2020-03-20,2020-03-23,2020-04-30
cash_dividends,a6587d80-e08a-4b1a-aa94-857549880c59,SPY,78462F103,1.366242,False,False,2020-07-31,2020-06-19,2020-06-22,2020-07-31
cash_dividends,ffb8940e-53fe-4b3e-a475-e15e39561d3d,SPY,78462F103,1.339224,False,False,2020-10-30,2020-09-18,2020-09-21,2020-10-30
cash_dividends,4d35e709-773b-46d4-b292-34d14c46f287,SPY,78462F103,1.580000,False,False,2021-01-29,2020-12-18,2020-12-21,2021-01-29
cash_dividends,f1ddda1e-b10c-4576-8253-4d8d5a149de6,SPY,78462F103,1.277788,False,False,2021-04-30,2021-03-19,2021-03-22,2021-04-30
cash_dividends,a06ac608-4210-4e4f-94f0-4fa342a8e1fd,SPY,78462F103,1.375875,False,False,2021-07-30,2021-06-18,2021-06-21,2021-07-30
cash_dividends,d2b09118-e4c0-4b93-9f46-10b211400773,SPY,78462F103,1.428117,False,False,2021-10-29,2021-09-17,2021-09-20,2021-10-29
cash_dividends,7cdc9442-1a32-4f40-9d2a-b721edfef9e9,SPY,78462F103,1.636431,False,False,2022-01-31,2021-12-17,2021-12-20,2022-01-31
cash_dividends,f5ca31fd-da0d-4651-be6b-6ac78542259e,SPY,78462F103,1.366009,False,False,2022-04-29,2022-03-18,2022-03-21,2022-04-29
cash_dividends,1f5b9849-96be-4d48-8c3a-b383dc2c544c,SPY,78462F103,1.576871,False,False,2022-07-29,2022-06-17,2022-06-21,2022-07-29
cash_dividends,377f7022-91cc-44da-9a8e-8bb00083d5a5,SPY,78462F103,1.596398,False,False,2022-10-31,2022-09-16,2022-09-19,2022-10-31
cash_dividends,0451d145-f55a-482f-9e11-8dad5910a801,SPY,78462F103,1.781400,False,False,2023-01-31,2022-12-16,2022-12-19,2023-01-31
cash_dividends,4bedbc95-3ce2-40fb-9a38-7d08717a69fc,SPY,78462F103,1.506204,False,False,2023-04-28,2023-03-17,2023-03-20,2023-04-28
cash_dividends,bbbff9be-c5e0-467e-87e0-396b636388b7,SPY,78462F103,1.638367,False,False,2023-07-31,2023-06-16,2023-06-20,2023-07-31
cash_dividends,774bf420-19e4-4ac1-b8b6-39e170496bd1,SPY,78462F103,1.583169,False,False,2023-10-31,2023-09-15,2023-09-18,2023-10-31
cash_dividends,0b715f27-57cc-4e72-975f-800ac009ecbd,SPY,78462F103,1.906073,False,False,2024-01-31,2023-12-15,2023-12-18,2024-01-31
cash_dividends,1788732d-92bc-47ba-89c8-dc3435a09b2a,SPY,78462F103,1.594937,False,False,2024-04-30,2024-03-15,2024-03-18,2024-04-30
cash_dividends,1eedcf06-a75b-4559-8215-2874546d6b80,SPY,78462F103,1.759024,False,False,2024-07-31,2024-06-21,2024-06-21,2024-07-31
cash_dividends,0429797e-504e-4571-855d-55d29cdb63d9,SPY,78462F103,1.745531,False,False,2024-10-31,2024-09-20,2024-09-20,2024-10-31
cash_dividends,24d33e88-e83b-467b-9832-821d2a97d4a5,SPY,78462F103,1.965548,False,False,2025-01-31,2024-12-20,2024-12-20,2025-01-31
cash_dividends,ed10c000-8a0b-44ba-a9d7-15f455b61d7a,SPY,78462F103,1.695528,False,False,2025-04-30,2025-03-21,2025-03-21,2025-04-30
cash_dividends,35139828-107b-4ab0-ad9d-91e4328f5cfa,SPY,78462F103,1.761117,False,False,2025-07-31,2025-06-20,2025-06-20,2025-07-31
cash_dividends,d7a29b12-db5d-41e5-8083-40c91e2091ff,SPY,78462F103,1.831114,False,False,2025-10-31,2025-09-19,2025-09-19,2025-10-31